### ISSUE TITLE
License of the module?

### ISSUE THREAD

**Issue by p91** [fgalindo/jekyll-liquid-latex-plugin#4]
Hi,

which license are you using for this module? GPL?
I am asking because the module is not really working for me so I rewrote parts of it to use pdflatex and convert. I would like to make my code public but as it is atm based on your code, I need to know which license you are using.

With best regards

**Comment by fgalindo** [comment]
Hello again,

MIT license. You can do what you want, only include a copy of the MIT license in your copy. But... wouldn't be better to just fork it?

**Comment by p91** [comment]
Hi,

well, to fork it I need to know in which legal trouble I am getting me. With MIT it is no problem but without any license (at least I haven't seen one here) the code is basically your property and forking it would be illegal (at least as far as I understand my local and the international copyright laws).
